import '../models/jurusan_models.dart';

List<Jurusan> daftarJurusan = [
  Jurusan(
    kode: 1,
    namaJurusan: 'Teknik Informatika',
    mtk: 0.35,
    binggris: 0.25,
    ips: 0.15,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 2,
    namaJurusan: 'Manajemen Bisnis',
    mtk: 0.2,
    binggris: 0.3,
    ips: 0.25,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 3,
    namaJurusan: 'Arsitektur',
    mtk: 0.3,
    binggris: 0.2,
    ips: 0.2,
    ipa: 0.3,
  ),
  Jurusan(
    kode: 4,
    namaJurusan: 'Kedokteran',
    mtk: 0.25,
    binggris: 0.3,
    ips: 0.2,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 5,
    namaJurusan: 'Hukum',
    mtk: 0.15,
    binggris: 0.4,
    ips: 0.4,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 6,
    namaJurusan: 'Pendidikan Matematika',
    mtk: 0.4,
    binggris: 0.15,
    ips: 0.2,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 7,
    namaJurusan: 'Ekonomi',
    mtk: 0.25,
    binggris: 0.3,
    ips: 0.35,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 8,
    namaJurusan: 'Psikologi',
    mtk: 0.15,
    binggris: 0.4,
    ips: 0.35,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 9,
    namaJurusan: 'Ilmu Komunikasi',
    mtk: 0.1,
    binggris: 0.45,
    ips: 0.35,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 10,
    namaJurusan: 'Teknik Elektro',
    mtk: 0.4,
    binggris: 0.2,
    ips: 0.2,
    ipa: 0.2,
  ),
  Jurusan(
    kode: 11,
    namaJurusan: 'Teknik Sipil',
    mtk: 0.3,
    binggris: 0.2,
    ips: 0.2,
    ipa: 0.3,
  ),
  Jurusan(
    kode: 12,
    namaJurusan: 'Farmasi',
    mtk: 0.2,
    binggris: 0.25,
    ips: 0.3,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 13,
    namaJurusan: 'Akuntansi',
    mtk: 0.25,
    binggris: 0.2,
    ips: 0.35,
    ipa: 0.2,
  ),
  Jurusan(
    kode: 14,
    namaJurusan: 'Agribisnis',
    mtk: 0.3,
    binggris: 0.25,
    ips: 0.2,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 15,
    namaJurusan: 'Seni Rupa',
    mtk: 0.15,
    binggris: 0.35,
    ips: 0.4,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 16,
    namaJurusan: 'Fisika',
    mtk: 0.4,
    binggris: 0.2,
    ips: 0.1,
    ipa: 0.3,
  ),
  Jurusan(
    kode: 17,
    namaJurusan: 'Biologi',
    mtk: 0.15,
    binggris: 0.2,
    ips: 0.2,
    ipa: 0.45,
  ),
  Jurusan(
    kode: 18,
    namaJurusan: 'Kimia',
    mtk: 0.3,
    binggris: 0.2,
    ips: 0.1,
    ipa: 0.4,
  ),
  Jurusan(
    kode: 19,
    namaJurusan: 'Teknik Kimia',
    mtk: 0.35,
    binggris: 0.2,
    ips: 0.15,
    ipa: 0.3,
  ),
  Jurusan(
    kode: 20,
    namaJurusan: 'Teknik Mesin',
    mtk: 0.4,
    binggris: 0.15,
    ips: 0.2,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 21,
    namaJurusan: 'Teknik Industri',
    mtk: 0.3,
    binggris: 0.2,
    ips: 0.2,
    ipa: 0.3,
  ),
  Jurusan(
    kode: 22,
    namaJurusan: 'Pendidikan Bahasa Inggris',
    mtk: 0.15,
    binggris: 0.45,
    ips: 0.3,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 23,
    namaJurusan: 'Pendidikan Fisika',
    mtk: 0.3,
    binggris: 0.15,
    ips: 0.15,
    ipa: 0.4,
  ),
  Jurusan(
    kode: 24,
    namaJurusan: 'Pendidikan Biologi',
    mtk: 0.15,
    binggris: 0.15,
    ips: 0.15,
    ipa: 0.55,
  ),
  Jurusan(
    kode: 25,
    namaJurusan: 'Pendidikan Kimia',
    mtk: 0.2,
    binggris: 0.15,
    ips: 0.15,
    ipa: 0.5,
  ),
  Jurusan(
    kode: 26,
    namaJurusan: 'Pendidikan Matematika',
    mtk: 0.35,
    binggris: 0.15,
    ips: 0.15,
    ipa: 0.35,
  ),
  Jurusan(
    kode: 27,
    namaJurusan: 'Teknik Pertanian',
    mtk: 0.3,
    binggris: 0.25,
    ips: 0.2,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 28,
    namaJurusan: 'Perhotelan',
    mtk: 0.2,
    binggris: 0.35,
    ips: 0.35,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 29,
    namaJurusan: 'Teknik Penerbangan',
    mtk: 0.4,
    binggris: 0.15,
    ips: 0.2,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 30,
    namaJurusan: 'Teknik Astronomi',
    mtk: 0.35,
    binggris: 0.15,
    ips: 0.15,
    ipa: 0.35,
  ),
  Jurusan(
    kode: 31,
    namaJurusan: 'Desain Grafis',
    mtk: 0.15,
    binggris: 0.35,
    ips: 0.4,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 32,
    namaJurusan: 'Bahasa Jepang',
    mtk: 0.1,
    binggris: 0.4,
    ips: 0.4,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 33,
    namaJurusan: 'Sastra Inggris',
    mtk: 0.15,
    binggris: 0.45,
    ips: 0.35,
    ipa: 0.05,
  ),
  Jurusan(
    kode: 34,
    namaJurusan: 'Agroteknologi',
    mtk: 0.25,
    binggris: 0.25,
    ips: 0.25,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 35,
    namaJurusan: 'Manajemen Keuangan',
    mtk: 0.2,
    binggris: 0.3,
    ips: 0.3,
    ipa: 0.2,
  ),
  Jurusan(
    kode: 36,
    namaJurusan: 'Ilmu Politik',
    mtk: 0.1,
    binggris: 0.4,
    ips: 0.45,
    ipa: 0.05,
  ),
  Jurusan(
    kode: 37,
    namaJurusan: 'Pariwisata',
    mtk: 0.2,
    binggris: 0.4,
    ips: 0.3,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 38,
    namaJurusan: 'Kesehatan Masyarakat',
    mtk: 0.1,
    binggris: 0.3,
    ips: 0.5,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 39,
    namaJurusan: 'Sosiologi',
    mtk: 0.15,
    binggris: 0.35,
    ips: 0.45,
    ipa: 0.05,
  ),
  Jurusan(
    kode: 40,
    namaJurusan: 'Manajemen Sumber Daya Manusia',
    mtk: 0.15,
    binggris: 0.35,
    ips: 0.35,
    ipa: 0.15,
  ),
  Jurusan(
    kode: 41,
    namaJurusan: 'Manajemen Pemasaran',
    mtk: 0.2,
    binggris: 0.35,
    ips: 0.3,
    ipa: 0.15,
  ),
  Jurusan(
    kode: 42,
    namaJurusan: 'Ilmu Gizi',
    mtk: 0.15,
    binggris: 0.3,
    ips: 0.45,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 43,
    namaJurusan: 'Ilmu Keperawatan',
    mtk: 0.2,
    binggris: 0.25,
    ips: 0.4,
    ipa: 0.15,
  ),
  Jurusan(
    kode: 44,
    namaJurusan: 'Ilmu Komputer',
    mtk: 0.35,
    binggris: 0.25,
    ips: 0.15,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 45,
    namaJurusan: 'Bahasa Mandarin',
    mtk: 0.1,
    binggris: 0.25,
    ips: 0.45,
    ipa: 0.2,
  ),
  Jurusan(
    kode: 46,
    namaJurusan: 'Teknik Telekomunikasi',
    mtk: 0.4,
    binggris: 0.2,
    ips: 0.15,
    ipa: 0.25,
  ),
  Jurusan(
    kode: 47,
    namaJurusan: 'Kedokteran Hewan',
    mtk: 0.15,
    binggris: 0.3,
    ips: 0.35,
    ipa: 0.2,
  ),
  Jurusan(
    kode: 48,
    namaJurusan: 'Desain Interior',
    mtk: 0.2,
    binggris: 0.35,
    ips: 0.3,
    ipa: 0.15,
  ),
  Jurusan(
    kode: 49,
    namaJurusan: 'Hubungan Internasional',
    mtk: 0.1,
    binggris: 0.4,
    ips: 0.4,
    ipa: 0.1,
  ),
  Jurusan(
    kode: 50,
    namaJurusan: 'Ilmu Perpustakaan',
    mtk: 0.15,
    binggris: 0.35,
    ips: 0.35,
    ipa: 0.15,
  ),
];
